CREATE USER 'e_user' @'%' IDENTIFIED BY 'Tam101096';

GRANT SELECT , INSERT , UPDATE , DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'e_user' @'%';

FLUSH PRIVILEGES;

SHOW GRANTS FOR 'e_user' @'%';

-- Create DB;
CREATE DATABASE tranvantamver2;