
-- CREATE USER 'e_user'@'localhost' IDENTIFIED BY 'e_Str0n6-p4s5w0Rd';
-- GRANT ALL ON *.* TO 'e_user'@'localhost';

-- WORKS at AWS
DROP USER 'e_user'@'%'; -- Skip this if the user not yet exist.
CREATE USER 'e_user'@'%' IDENTIFIED BY 'e_Str0n6-p4s5w0Rd';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER  ON *.* TO 'e_user'@'%';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'e_user'@'%';


-- Create DB;
CREATE DATABASE e_db_1;
