ALTER TABLE `accessory` ADD UNIQUE INDEX `code_id` USING BTREE(`code_id`);
ALTER TABLE `accessory` ADD PRIMARY KEY USING BTREE(`seq_id`);
ALTER TABLE `accessory` MODIFY COLUMN `seq_id` INTEGER) UNSIGNED NOT NULL AUTO_INCREMENT;
