ALTER TABLE `master_user` ADD PRIMARY KEY USING BTREE(`seq_id`);
ALTER TABLE `master_user` ADD UNIQUE INDEX `user_name` USING BTREE(`username`);
ALTER TABLE `master_user` MODIFY COLUMN `seq_id` INTEGER) UNSIGNED NOT NULL AUTO_INCREMENT;
