ALTER TABLE `car` ADD INDEX `entity_code` USING BTREE(`entity_code`);
ALTER TABLE `car` ADD UNIQUE INDEX `license_plate` USING BTREE(`license_plate`);
ALTER TABLE `car` ADD INDEX `maker` USING BTREE(`maker`);
ALTER TABLE `car` ADD INDEX `model` USING BTREE(`model`);
ALTER TABLE `car` ADD PRIMARY KEY USING BTREE(`seq_id`);
ALTER TABLE `car` ADD INDEX `status` USING BTREE(`status`);
ALTER TABLE `car` MODIFY COLUMN `seq_id` INTEGER) UNSIGNED NOT NULL AUTO_INCREMENT;
