CREATE TABLE IF NOT EXISTS `master_dev` (
  `seq_id` int unsigned NOT NULL AUTO_INCREMENT,
  `approval_status` varchar(32) DEFAULT NULL,
  `user_id` varchar(64) DEFAULT NULL,
  `user_shimei` varchar(64) DEFAULT NULL,
  `role` varchar(64) DEFAULT NULL,
  `company` varchar(64) DEFAULT NULL,
  `department` varchar(64) DEFAULT NULL,
  `team` varchar(64) DEFAULT NULL,
  `login_failure_count` int NOT NULL DEFAULT '0',
  `password` varchar(128) NOT NULL,
  `mail_address` varchar(64) DEFAULT NULL,
  `salt` varchar(36) NOT NULL,
  `last_login_date` datetime DEFAULT NULL,
  `approval_status_flag` int NOT NULL DEFAULT '0',
  `last_changed_fields` varchar(4048) DEFAULT NULL,
  `last_changed_data` varchar(4048) DEFAULT NULL,
  `last_password_changed_date` date DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `zoom_info` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`seq_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;